version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./ci/nginx/conf.d/:/etc/nginx/conf.d/
      - ./ci/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/:/var/log/
    depends_on:
      - web
    ports:
      - "8079:8080"
  web:
    build: .
    image: tonghs/web-template
    command: bash -c './dev.sh'
    volumes:
      - .:/opt/code
      - /var/log/web-template/:/var/log/web-template/
    environment:
      - PYTHONPATH=/opt/code
      - DEBUG=1
      - GUNICORN_WORKERS=1
      - GUNICORN_BIND_ADDRESS=0.0.0.0:5000
      - GUNICORN_LOG_LEVEL=DEBUG
      - GUNICORN_RELOAD=--reload
      - GUNICORN_ACCESS_LOGFILE=-
      - PYTHONUNBUFFERED=TRUE
      - LOG_PATH=/var/log/web-template

    healthcheck:
      test: "curl -f http://localhost:5000/ping || exit 1"
      retries: 3
      interval: 30s
      timeout: 30s
    restart: always
