version: '3.7'
services:
  web:
    build: .
    image: tonghs/cdm
    command: bash -c './dev.sh'
    volumes:
      - .:/opt/code
      - /var/log/cdm/:/var/log/cdm/
    environment:
      - PYTHONPATH=/opt/code
      - PYTHONUNBUFFERED=TRUE
      - DEBUG=1

    ports:
    - "8079:8079"


    restart: always
