version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./ci/nginx/conf.d/:/etc/nginx/conf.d/
      - ./ci/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log:/var/log
    depends_on:
      - web
    ports:
      - "8079:8080"
  web:
    build: .
    image: tonghs/web-template
    command: bash -c './dev.sh'
    volumes:
      - .:/opt/code
      - /var/log:/var/log
    environment:
      - PYTHONPATH=/opt/code
      - DEBUG=0
      - GUNICORN_WORKERS=1
      - GUNICORN_BIND_ADDRESS=0.0.0.0:5000
      - GUNICORN_LOG_LEVEL=DEBUG
      - GUNICORN_RELOAD=--reload
      - GUNICORN_ACCESS_LOGFILE=-
      - PYTHONUNBUFFERED=TRUE
      - MYSQL_HOST=${MYSQL_HOST:-db}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWD=${MYSQL_PASSWD:-tonghs}
      - MYSQL_DB=${MYSQL_DB:-web-template}
      - LOG_PATH=/var/log/web-template
      - WXAPP_ID=${WXAPP_ID:-wxapp_id}
      - WXAPP_SECRET=${WXAPP_SECRET:-wxapp_secret}
    healthcheck:
      test: "curl -f http://localhost:5000/ping || exit 1"
      retries: 3
      interval: 30s
      timeout: 30s
    restart: always
