version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./ci/nginx/web.conf:/etc/nginx/conf.d/web.conf
      - /var/log:/var/log
    depends_on:
      - web
    ports:
      - "8079:8080"
  web:
    build: .
    image: tonghs/web-template
    volumes:
      - .:/opt/code
      - /var/log:/var/log
    environment:
      - DEBUG=0
      - GUNICORN_WORKERS=1
      - GUNICORN_BIND_ADDRESS=0.0.0.0:5000
      - GUNICORN_LOG_LEVEL=info
      - GUNICORN_RELOAD=--reload
    healthcheck:
      test: "curl -f http://localhost:5000/ping || exit 1"
      retries: 3
      interval: 30s
      timeout: 30s
    restart: always
    scale: 1
