version: '3.7'
services:
  db:
    command:
     --lower_case_table_names=1
     --character-set-server=utf8mb4
     --collation-server=utf8mb4_general_ci
     --explicit_defaults_for_timestamp=true
    image: mysql:5.7

    environment:
     - TZ=Asia/Shanghai
     - MYSQL_HOST=192.168.44.6
     - MYSQL_PORT=3306
     - MYSQL_ROOT_PASSWORD=tonghs
     - MYSQL_USER=tonghs
     - MYSQL_PASSWORD=tonghs
     - MYSQL_DB=web-template
    networks:
      default:
        aliases:
          - test-db

  redis:
    image: 'redis:latest'
    networks:
      default:
        aliases:
          - test-redis
