version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./ci/nginx/conf.d/:/etc/nginx/conf.d/
      - ./ci/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log:/var/log
    depends_on:
      - web
    ports:
      - "8079:8080"
  web:
    build: .
    image: tonghs/web-template
    volumes:
      - .:/opt/code
      - /var/log:/var/log
      - ./ci/hosts:/etc/hosts
    environment:
      - DEBUG=0
      - PYTHONPATH=/opt/code
      - GUNICORN_WORKERS=4
      - GUNICORN_BIND_ADDRESS=0.0.0.0:5000
      - GUNICORN_LOG_LEVEL=WARN
      - GUNICORN_RELOAD=
      - GUNICORN_ACCESS_LOGFILE=-
      - MYSQL_HOST=${MYSQL_HOST:-db}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWD=${MYSQL_PASSWD:-tonghs}
      - MYSQL_DB=${MYSQL_DB:-web-template}
      - JWT_SECRET=${JWT_SECRET:-your-secret}
      - API_SECRET=${API_SECRET:-your-secret}
      - WXAPP_ID=${WXAPP_ID:-your-wxapp-id}
      - WXAPP_SECRET=${WXAPP_SECRET:-your-wxapp-secret}
      - LOG_PATH=/var/log/web-template
    healthcheck:
      test: "curl -f http://localhost:5000/ping || exit 1"
      retries: 3
      interval: 10s
      timeout: 30s
    restart: always
    scale: 4
