---
- hosts: web
  remote_user: tonghs
  tasks:
  - name: update web repo
    shell: cd /home/tonghs/app/cdm && git pull --rebase

  - name: start web service
    shell: cd /home/tonghs/app/cdm && sudo make run-server
