---
- hosts: web
  remote_user: tonghs
  tasks:
  - name: update web repo
    shell: cd /home/tonghs/app/web-template && git pull --rebase

  - name: start web service
    shell: cd /home/tonghs/app/web-template && sudo make run-server
