name: Test PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sed -i 's/COPY ci\/sources.list \/etc\/apt\/sources.list//g' Dockerfile
      - run: sed -i 's/http:\/\/mirrors.aliyun.com\/pypi\/simple\/ --extra-index-url https:\/\/pypi.python.org\/simple --trusted-host mirrors.aliyun.com/ /g' Dockerfile
      - run: sed -i 's/http:\/\/mirrors.aliyun.com\/pypi\/simple\/ --extra-index-url https:\/\/pypi.python.org\/simple --trusted-host mirrors.aliyun.com/ /g' docker-compose.test.yml
      - run: sed -i 's/ipython//g' requirements.txt
      - run: sed -i 's/gunicorn==.*//g' requirements.txt
      - run: sed -i 's/gevent==.*//g' requirements.txt
      - run: sed -i 's/psutil==.*//g' requirements.txt
      - run: cp config.sample.py config.py &&  docker-compose -f docker-compose.yml up -d
      - run: make test
