name: merge to main branch

on:
  push:
    branches: main

jobs:
  test_main_branch:
    name: test main branch, build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sed -i 's/COPY ci\/sources.list \/etc\/apt\/sources.list//g' Dockerfile
          sed -i 's/ -i http:\/\/mirrors.aliyun.com\/pypi\/simple\/ --extra-index-url https:\/\/pypi.python.org\/simple --trusted-host mirrors.aliyun.com/ /g' Dockerfile
          sed -i 's/ -i http:\/\/mirrors.aliyun.com\/pypi\/simple\/ --extra-index-url https:\/\/pypi.python.org\/simple --trusted-host mirrors.aliyun.com/ /g' docker-compose.test.yml
          sed -i 's/ipython//g' requirements.txt
          sed -i 's/--cov-report=html/--cov-report=xml/g' ci/run_test.sh
          cp config.sample.py config.py && docker-compose -f docker-compose.yml up -d
      - run: make test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tonghs/cdm:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
